### ISSUE TITLE
Install not working?

### ISSUE THREAD

**Issue by montorod** [mtoto/ufc.stats#4]
> devtools::install_github("mtoto/ufc.stats")
Downloading GitHub repo mtoto/ufc.stats@master
from URL https://api.github.com/repos/mtoto/ufc.stats/zipball/master
Installing ufc.stats
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpvepj4G/devtools6c74ad63f03/mtoto-ufc.stats-ee63812' --library='/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘ufc.stats’ ...
** R
** data
*** moving datasets to lazyload DB
Warning: file ‘ufc_stats.rda’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = envir) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package ‘ufc.stats’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4/ufc.stats’
Installation failed: Command failed (1)

**Comment by mtoto** [comment]
@montorod can't reproduce, does this issue still persist?
